import Link from "next/link"
import { ArrowRight, Axe, Clock, Hammer, MapPin } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import SiteHeader from "@/components/SiteHeader"
import Footer from "@/components/Footer"
import { locationList } from "@/lib/locations"

export default function ClientPage() {
  return <main className="min-h-screen bg-background text-foreground">
    <SiteHeader />
    <section className="relative overflow-hidden border-b border-border bg-card py-16 md:py-24 lg:py-28">
      <div className="container mx-auto grid max-w-7xl gap-12 px-4 sm:px-6 lg:grid-cols-[1.1fr_.9fr] lg:items-center">
        <div><p className="mb-4 font-mono text-sm font-bold uppercase tracking-widest text-secondary">Portland · St. Johns · Tualatin</p><h1 className="text-balance font-serif text-5xl font-black uppercase leading-none md:text-7xl lg:text-8xl">Break stuff. Throw axes. <span className="text-primary">Pick your side of town.</span></h1><p className="mt-6 max-w-2xl text-pretty text-lg leading-relaxed text-muted-foreground">Portland&apos;s rage room and axe throwing experience now has two locations. Choose the one closest to you, compare hours, and book in a few clicks.</p></div>
        <div id="locations" className="grid gap-4" aria-label="Choose a location">{locationList.map((location, index) => <Card key={location.slug} className="group bg-background transition-colors hover:border-secondary"><CardHeader className="flex-row items-start justify-between gap-4"><div><p className="font-mono text-xs font-bold uppercase tracking-widest text-secondary">Location 0{index + 1}</p><CardTitle className="mt-2 font-serif text-3xl uppercase">{location.shortName}</CardTitle><CardDescription className="mt-2">{location.intro}</CardDescription></div><MapPin className="text-primary" aria-hidden="true" /></CardHeader><CardContent><p className="text-sm text-muted-foreground">{location.address}</p><p className="mt-2 flex items-center gap-2 text-sm"><Clock aria-hidden="true" />{location.slug === "st-johns" ? "Open Tue–Sun" : "Open Wed–Sun"}</p></CardContent><CardFooter><Button asChild className="w-full"><Link href={`/locations/${location.slug}`}>View {location.shortName} & book<ArrowRight data-icon="inline-end" /></Link></Button></CardFooter></Card>)}</div>
      </div>
    </section>
    <section className="py-16 md:py-24"><div className="container mx-auto max-w-7xl px-4 sm:px-6"><div className="max-w-3xl"><p className="font-mono text-sm font-bold uppercase tracking-widest text-secondary">One lineup. Two locations.</p><h2 className="mt-3 text-balance font-serif text-4xl font-black uppercase md:text-6xl">Choose your kind of chaos</h2><p className="mt-5 text-lg leading-relaxed text-muted-foreground">Every visit includes equipment and a safety briefing. No experience required—just closed-toe shoes and a willingness to make some noise.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{[{icon:Hammer,title:"Rage Room",copy:"Smash recyclable bottles, electronics, and more in a private destruction space.",price:"From $35"},{icon:Axe,title:"Axe Throwing",copy:"Learn the basics from our team, then settle into a satisfying throwing rhythm.",price:"From $25"},{icon:ArrowRight,title:"Rage + Axe",copy:"Why choose? Pair a throwing session with the full rage room release.",price:"From $45"}].map((item) => <Card key={item.title} className="bg-card"><CardHeader><item.icon className="mb-3 text-primary" aria-hidden="true" /><CardTitle className="font-serif text-2xl uppercase">{item.title}</CardTitle><CardDescription className="leading-relaxed">{item.copy}</CardDescription></CardHeader><CardContent><p className="text-xl font-black text-secondary">{item.price}</p></CardContent></Card>)}</div><div className="mt-10"><Button asChild size="lg"><Link href="/book">Choose location & book<ArrowRight data-icon="inline-end" /></Link></Button></div></div></section>
    <section className="border-y border-border bg-card py-16"><div className="container mx-auto grid max-w-6xl gap-8 px-4 sm:px-6 md:grid-cols-2"><div><h2 className="font-serif text-3xl font-black uppercase">Built for groups</h2><p className="mt-4 leading-relaxed text-muted-foreground">Birthday parties, team outings, date nights, bachelor and bachelorette groups—bring your people and we&apos;ll help you build the right session.</p><Button asChild variant="outline" className="mt-6"><Link href="/parties-events">Plan a group visit</Link></Button></div><div><h2 className="font-serif text-3xl font-black uppercase">First time?</h2><p className="mt-4 leading-relaxed text-muted-foreground">Learn what to wear, when to arrive, what you can smash, and how our safety briefing works before you book.</p><Button asChild variant="outline" className="mt-6"><Link href="/how-it-works">See how it works</Link></Button></div></div></section>
    <Footer />
  </main>
}
