import Link from "next/link"
import { ArrowRight, Axe, Clock, Hammer, MapPin } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import SiteHeader from "@/components/SiteHeader"
import Footer from "@/components/Footer"
import { locationList } from "@/lib/locations"

export default function ClientPage() {
  return <main className="min-h-screen bg-background text-foreground">
    <SiteHeader />
    <section className="relative overflow-hidden border-b border-border bg-card py-16 md:py-24 lg:py-28">
      <video autoPlay muted loop playsInline preload="metadata" aria-hidden="true" tabIndex={-1} className="pointer-events-none absolute inset-0 size-full object-cover motion-reduce:hidden">
        <source src="/videos/rage-room-hero.mp4" type="video/mp4" />
      </video>
      <div className="absolute inset-0 bg-background/80" aria-hidden="true" />
      <div className="relative container mx-auto grid max-w-7xl gap-12 px-4 sm:px-6 lg:grid-cols-[1.1fr_.9fr] lg:items-center">
        <div><p className="mb-4 font-mono text-sm font-bold uppercase tracking-widest text-secondary">Portland&apos;s rage room · Two locations</p><h1 className="text-balance font-serif text-5xl font-black uppercase leading-none md:text-7xl lg:text-8xl">Smash stress. Break stuff. <span className="text-primary">Choose your rage room.</span></h1><p className="mt-6 max-w-2xl text-pretty text-lg leading-relaxed text-foreground">Book a private rage room in St. Johns or Tualatin and let it all out in a safe, controlled space. Want more? Add axe throwing or make it a combo.</p></div>
        <div id="locations" className="grid gap-4" aria-label="Choose a location">{locationList.map((location, index) => <Card key={location.slug} className="neon-border-hover group bg-background/90 shadow-xl backdrop-blur-sm"><CardHeader className="flex-row items-start justify-between gap-4"><div><p className="font-mono text-xs font-bold uppercase tracking-widest text-secondary">Location 0{index + 1}</p><CardTitle className="mt-2 font-serif text-3xl uppercase">{location.shortName}</CardTitle><CardDescription className="mt-2">{location.intro}</CardDescription></div><MapPin className="text-primary" aria-hidden="true" /></CardHeader><CardContent><p className="text-sm text-muted-foreground">{location.address}</p><p className="mt-2 flex items-center gap-2 text-sm"><Clock aria-hidden="true" />{location.slug === "st-johns" ? "Open Tue–Sun" : "Open Wed–Sun"}</p></CardContent><CardFooter><Button asChild className="w-full"><Link href={`/locations/${location.slug}`}>View {location.shortName} & book<ArrowRight data-icon="inline-end" /></Link></Button></CardFooter></Card>)}</div>
      </div>
    </section>
    <section className="py-16 md:py-24"><div className="container mx-auto max-w-7xl px-4 sm:px-6"><div className="max-w-3xl"><p className="font-mono text-sm font-bold uppercase tracking-widest text-secondary">Rage rooms first. More ways to play.</p><h2 className="mt-3 text-balance font-serif text-4xl font-black uppercase md:text-6xl">Come here to smash</h2><p className="mt-5 text-lg leading-relaxed text-muted-foreground">Your rage room session is the main event: a private space, breakable items, protective equipment, and a safety briefing. No experience required—just closed-toe shoes and a willingness to make some noise.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{[{icon:Hammer,title:"Rage Room",copy:"The reason you're here. Smash recyclable bottles, electronics, and more in a private destruction space.",price:"From $35"},{icon:ArrowRight,title:"Rage + Axe Add-On",copy:"Start with the full rage room release, then add axe throwing to keep the energy going.",price:"From $45"},{icon:Axe,title:"Axe Throwing Bonus",copy:"Axe throwing is also available when your group wants another activity alongside the smash.",price:"From $25"}].map((item) => <Card key={item.title} className="neon-border-hover bg-card"><CardHeader><item.icon className="mb-3 text-primary" aria-hidden="true" /><CardTitle className="font-serif text-2xl uppercase">{item.title}</CardTitle><CardDescription className="leading-relaxed">{item.copy}</CardDescription></CardHeader><CardContent><p className="text-xl font-black text-secondary">{item.price}</p></CardContent></Card>)}</div><div className="mt-10"><Button asChild size="lg"><Link href="/book">Choose location & book<ArrowRight data-icon="inline-end" /></Link></Button></div></div></section>
    <section className="border-y border-border bg-card py-16"><div className="container mx-auto grid max-w-6xl gap-8 px-4 sm:px-6 md:grid-cols-2"><div><h2 className="font-serif text-3xl font-black uppercase">Built for groups</h2><p className="mt-4 leading-relaxed text-muted-foreground">Birthday parties, team outings, date nights, bachelor and bachelorette groups—bring your people and we&apos;ll help you build the right session.</p><Button asChild variant="outline" className="mt-6"><Link href="/parties-events">Plan a group visit</Link></Button></div><div><h2 className="font-serif text-3xl font-black uppercase">First time?</h2><p className="mt-4 leading-relaxed text-muted-foreground">Learn what to wear, when to arrive, what you can smash, and how our safety briefing works before you book.</p><Button asChild variant="outline" className="mt-6"><Link href="/how-it-works">See how it works</Link></Button></div></div></section>
    <Footer />
  </main>
}
